# Generated by Django 5.2.11 on 2026-02-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='street',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.JSONField(default='old'),
            preserve_default=False,
        ),
    ]
